name: "update pacakges"

permissions: {}

on:
  workflow_dispatch:
    inputs:
      upterm:
        description: "Start upterm session after nix build"
        required: true
        type: boolean
        default: false
  schedule:
    # Run at an odd time to avoid spikes at, e.g. midnight.
    # We don't really care too much about the particular time.
    # https://crontab.guru/#17_1_*_*_Mon
    - cron: "17 1 * * Mon"

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false, fetch-depth: 0, ref: main }
      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Update all packages
        id: update-packages
        run: |
          nix-shell --run 'update-all --commit' | tee /tmp/update-all.log

          {
            echo "UPDATES<<EOF"
            git log origin/main..HEAD --format="- %s"
            echo "EOF"
          } >> "$GITHUB_ENV"

          {
            echo "UPDATES_FAILED<<EOF"
            sed -n '/Failed to update the following packages:/,$p' /tmp/update-all.log
            echo "EOF"
          } >> "$GITHUB_ENV"
      - uses: actions/upload-artifact@v4
        with:
          name: update-all.log
          path: update-all.log
      - name: Create Pull Request
        if: env.UPDATES != ''
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          sign-commits: true
          title: "ci: Update packages"
          branch: "update_packages"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          labels: |
            automated
          body: |
            The following packages have been automatically updated by GitHub Action:

            ${{ env.UPDATES }}

            <details><summary>Failed to update:</summary>
            <p>

            ```
            ${{ env.UPDATES_FAILED }}
            ```

            </p>
            </details>
      - name: start upterm session
        if: ${{ inputs.upterm }}
        uses: owenthereal/action-upterm@2f4c8d6df06230280f48b80e87c4edc6cf2cf890 # v1.5.0
        with:
          limit-access-to-actor: true
