name: update

permissions: {}

on:
  workflow_dispatch:
  schedule:
    # Run at an odd time to avoid spikes at, e.g. midnight.
    # We don't really care too much about the particular time.
    # https://crontab.guru/#17_1_*_*_Mon
    - cron: "17 1 * * Mon"

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false }
      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
      - uses: DeterminateSystems/update-flake-lock@db4ee38117a597ea8df8f7f75a187dd65093eade # v23
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          pr-title: "flake: Update flake.lock"
          pr-labels: |
            automated
  update-scripts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with: { persist-credentials: false, fetch-depth: 0, ref: main }
      - uses: cachix/install-nix-action@7be5dee1421f63d07e71ce6e0a9f8a4b07c2a487 # v31.6.1
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Update all packages
        run: |
          git fetch origin
          nix-shell --run 'update meta-press --commit'
          echo "UPDATES=$(git log main..HEAD --format="- %s")" >> "$GITHUB_ENV"
      - name: Create Pull Request
        # if: env.UPDATES != ''
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          sign-commits: true
          title: "ci: Update packages"
          branch: "update_packages"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          labels: |
            automated
          body: |
            The following packages have been automatically updated by GitHub Action:

            ${{ env.UPDATES }}
